---
name: Catalyst-Plugin-Breadcrumbs
version: 3
author:
  - 'Danial Pearce <cpan@tigris.id.au>'
abstract: Breadcrumb information for your templates.
license: perl
requires:
  Catalyst: 5.2
provides:
  Catalyst::Plugin::Breadcrumbs:
    file: lib/Catalyst/Plugin/Breadcrumbs.pm
    version: 3
generated_by: Module::Build version 0.2611
